# Generated by Django 6.0.1 on 2026-06-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="addclients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=30)),
                ("ccp", models.DecimalField(decimal_places=2, max_digits=20)),
                ("cle", models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
