# Generated by Django 6.0.1 on 2026-06-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addnew", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addclients",
            name="ccp",
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name="addclients",
            name="cle",
            field=models.IntegerField(max_length=30),
        ),
    ]
